spring:
    jpa:
        database: MYSQL
        hibernate:
          ddl-auto: update
          show_sql: true
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://localhost:3306/backendninja?useSSL=false
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false